### ISSUE TITLE
Misaligned hotspots in Oculus

### ISSUE THREAD

**Issue by GarvitArya** [IdeaSpaceVR/IdeaSpace-360-Photo-Tour#5]
The navigation hotspots are aligned properly in mobile devices and on laptops but, on Oculus rift it is showing misaligned hotspots.

**Comment by weddingdj** [comment]
I fixed some bugs, could you test this theme preview if the hotspots are still misaligned?

https://www.ideaspacevr.org/theme-preview/ideaspace-360-photo-tour

**Comment by GarvitArya** [comment]
I checked in this sample also its getting misaligned. So when I move the headset the hotspots also move randomly in all dimensions. Sometimes it is showing the hotspots in the center of room as well

**Comment by weddingdj** [comment]
It works for me in the Rift, using latest Firefox or Supermedium (did not try Chrome lately). Which browser and which browser version are you using?

**Comment by GarvitArya** [comment]
I am using Firefox nightly ver 61. Was not able to use supermedium. Can you please check my site if it is working for you: http://vrdreamz.in/VR_Dreamz/sample-tour1

**Comment by weddingdj** [comment]
I use Firefox 59 and it says it is the latest version. You don't need Firefox Nightly anymore, Mozilla officially launched WebVR since a couple of months. It could be that FF Nightly is unstable.

I checked your site and it works well in the Rift.

**Comment by weddingdj** [comment]
And it works well in Supermedium as well, I just tested it again.

**Comment by GarvitArya** [comment]
Okay, thanks a lot for the help. I will test it in Firefox and will revert back if I need any other help.

**Comment by GarvitArya** [comment]
I checked with Firefox 59, the issue still persists. So the hotspots look fine when you try to look 360 standing  at a single position but when you try to move around physically looking at those hotspots it start moving randomly here and there. Is there anything I am missing out? My windows in win 10 and oculus app ver is 1.25

**Comment by weddingdj** [comment]
I tested your link again in Firefox 59 and Oculus 1.26 (I don't think this plays a role). I can walk close up to the hotspots and they stay where they are. Do they move randomly only if you walk around them? Could this be an Oculus tracking issue on your side (walking outside tracking area)? Is it also happening when you walk around the box at the start of the scene?

**Comment by GarvitArya** [comment]
Thanks dude, yeah for me the spots move randomly when I walk physically here and there looking at any mark. I am not moving outside tracking area though. I am facing same issue in supermedium also. Will try using Vive once. It seems when we move oculus headset here and there, its sensor coordinates make hotspots move. And the link you provided works fine in my oculus.

**Comment by GarvitArya** [comment]
Something like this:

![img-20180509-wa0000](https://user-images.githubusercontent.com/10580694/39908599-6c205500-550c-11e8-8958-94977d3f931b.jpg)

**Comment by GarvitArya** [comment]
Also, when you said  that "you managed to walk around"..was it using controllers or did you literally tried moving physically? As this is happening in case of actual movement.

**Comment by GarvitArya** [comment]
Okay...thanks a lot dude..will try to figure out from oculus side then
